import Head from 'next/head';
import 'styles/globals.scss';

function CreateNextApp({ Component, pageProps }) {
  return (
    <div id="create-next-app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </div>
  );
}

export default CreateNextApp;
